image: node:10-alpine

variables:
  DOCKER_DRIVER: overlay2

stages:
  - install
  - test
  - build
  - docker
  - deploy
  - cleanup

install:
  stage: install
  script: yarn
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/

test:
  stage: test
  script: yarn test
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  artifacts:
    reports:
      junit: reports/junitresults.xml
    paths:
      - reports

lint:
  stage: test
  script: yarn lint
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/

flow:
  image: node:10
  stage: test
  script: yarn flow
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/

build:
  stage: build
  variables:
    NODE_ENV: production
  script: yarn build
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist
  dependencies: []

# codecov:
#   stage: build
#   script: yarn test:codecov
#   cache:
#     policy: pull
#     key: '$CI_COMMIT_REF_SLUG'
#     paths:
#       - node_modules/
#   dependencies:
#     - test

docker:
  services:
    - docker:dind
  image: registry.gitlab.com/marudor/deploy-helper/docker
  stage: docker
  script:
    - /build.sh
  dependencies:
    - build


deploy:pingu:
  image: registry.gitlab.com/marudor/deploy-helper
  stage: deploy
  script: /deploy.sh "pingu" "$CI_COMMIT_SHA" "pictures"
  environment:
    name: pingu
  when: manual
  dependencies: []

deploy:tiger:
  image: registry.gitlab.com/marudor/deploy-helper
  stage: deploy
  script: /deploy.sh "tiger" "$CI_COMMIT_SHA" "pictures"
  environment:
    name: tiger
  when: manual
  dependencies: []

deploy:panda:
  image: registry.gitlab.com/marudor/deploy-helper
  stage: deploy
  script: /deploy.sh "panda" "$CI_COMMIT_SHA" "pictures"
  environment:
    name: panda
  when: manual
  dependencies: []

deploy:fox:
  image: registry.gitlab.com/marudor/deploy-helper
  stage: deploy
  script: /deploy.sh "fox" "$CI_COMMIT_SHA" "pictures"
  environment:
    name: fox
  when: manual
  dependencies: []

deploy:cats:
  image: registry.gitlab.com/marudor/deploy-helper
  stage: deploy
  script: /deploy.sh "cats" "$CI_COMMIT_SHA" "pictures"
  environment:
    name: cats
  when: manual
  dependencies: []


cleanup:
  stage: cleanup
  image: registry.gitlab.com/marudor/deploy-helper
  script:
    - /cleanup.sh "pictures"
  dependencies: []
